# Generated by Django 5.0.7 on 2024-08-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/default.jpg', upload_to='projects/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
