# Generated by Django 5.0.7 on 2024-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_project_analysis_results_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='is_data_analysis',
            field=models.BooleanField(default=False),
        ),
    ]
